base-heart-health: 100
tower-heart-material: RED_GLAZED_TERRACOTTA
lobby:
  x: 0.5
  y: 0.0
  z: 0.5
  yaw: 0
  pitch: 0
  world: world
maps:
  default:
    teams:
      RED:
        heart:
          x: 0
          y: 0
          z: 0
        spawn:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0
          pitch: 0.0
      BLUE:
        heart:
          x: 0
          y: 0
          z: 0
        spawn:
          x: 0.0
          y: 0.0
          z: 0.0
          yaw: 0.0
          pitch: 0.0
    supply-crate:
      x: 0.0
      y: 0.0
      z: 0.0
    waiting-room:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    world: world
